/**
 * Aerospace Forces image paths under public/assets/vehicles/russia/aerospace_forces.
 * Generated by: node scripts/list-aerospace-forces-images.cjs
 * Do not edit by hand; re-run the script after adding or renaming images.
 */
export const AEROSPACE_FORCES_IMAGE_PATHS: string[] = [
  "/assets/vehicles/russia/aerospace_forces/Beriev A-50U/Beriev A-50U_01.png",
  "/assets/vehicles/russia/aerospace_forces/Beriev A-50U/Beriev A-50U_02.png",
  "/assets/vehicles/russia/aerospace_forces/Ilyushin Il-76MD-90A/Ilyushin Il-76MD-90A_01.png",
  "/assets/vehicles/russia/aerospace_forces/Ilyushin Il-76MD-90A/Ilyushin Il-76MD-90A_02.png",
  "/assets/vehicles/russia/aerospace_forces/Ilyushin Il-78/Ilyushin Il-78_01.png",
  "/assets/vehicles/russia/aerospace_forces/Ilyushin Il-78/Ilyushin Il-78_02.png",
  "/assets/vehicles/russia/aerospace_forces/Kamov Ka-52/Kamov Ka-52_01.png",
  "/assets/vehicles/russia/aerospace_forces/Kamov Ka-52/Kamov Ka-52_02.png",
  "/assets/vehicles/russia/aerospace_forces/Mikoyan MiG-31/Mikoyan MiG-31_01.png",
  "/assets/vehicles/russia/aerospace_forces/Mikoyan MiG-31/Mikoyan MiG-31_02.png",
  "/assets/vehicles/russia/aerospace_forces/Mil Mi-8AMTSh/Mil Mi-8AMTSh_01.png",
  "/assets/vehicles/russia/aerospace_forces/Mil Mi-8AMTSh/Mil Mi-8AMTSh_02.png",
  "/assets/vehicles/russia/aerospace_forces/S-400 Triumf/S-400 Triumf_01.png",
  "/assets/vehicles/russia/aerospace_forces/S-400 Triumf/S-400 Triumf_02.png",
  "/assets/vehicles/russia/aerospace_forces/Sukhoi Su-34/Sukhoi Su-34_01.png",
  "/assets/vehicles/russia/aerospace_forces/Sukhoi Su-34/Sukhoi Su-34_02.png",
  "/assets/vehicles/russia/aerospace_forces/Sukhoi Su-35S/Sukhoi Su-35S_01.png",
  "/assets/vehicles/russia/aerospace_forces/Sukhoi Su-35S/Sukhoi Su-35S_02.png",
  "/assets/vehicles/russia/aerospace_forces/Sukhoi Su-57/Sukhoi Su-57_01.png",
  "/assets/vehicles/russia/aerospace_forces/Sukhoi Su-57/Sukhoi Su-57_02.png",
  "/assets/vehicles/russia/aerospace_forces/Tupolev Tu-160/Tupolev Tu-160_01.png",
  "/assets/vehicles/russia/aerospace_forces/Tupolev Tu-160/Tupolev Tu-160_02.png",
  "/assets/vehicles/russia/aerospace_forces/Tupolev Tu-22M3/Tupolev Tu-22M3_01.png",
  "/assets/vehicles/russia/aerospace_forces/Tupolev Tu-22M3/Tupolev Tu-22M3_02.png",
  "/assets/vehicles/russia/aerospace_forces/Tupolev Tu-95MS/Tupolev Tu-95MS_01.png",
  "/assets/vehicles/russia/aerospace_forces/Tupolev Tu-95MS/Tupolev Tu-95MS_02.png"
]
