/**
 * Aerospace Forces image paths under public/assets/suorituskyvyt/03-ilma-avaruusvoimat.
 * Generated by: node scripts/list-aerospace-forces-images.cjs
 * Do not edit by hand; re-run the script after adding or renaming images.
 */
export const AEROSPACE_FORCES_IMAGE_PATHS: string[] = [
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/beriev-a-50u/beriev-a-50u-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/beriev-a-50u/beriev-a-50u-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/ilyushin-il-76md-90a/ilyushin-il-76md-90a-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/ilyushin-il-76md-90a/ilyushin-il-76md-90a-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/ilyushin-il-78/ilyushin-il-78-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/ilyushin-il-78/ilyushin-il-78-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/kamov-ka-52/kamov-ka-52-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/kamov-ka-52/kamov-ka-52-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/mikoyan-mig-31/mikoyan-mig-31-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/mikoyan-mig-31/mikoyan-mig-31-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/mil-mi-8amtsh/mil-mi-8amtsh-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/mil-mi-8amtsh/mil-mi-8amtsh-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/s-400-triumf/s-400-triumf-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/s-400-triumf/s-400-triumf-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/sukhoi-su-34/sukhoi-su-34-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/sukhoi-su-34/sukhoi-su-34-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/sukhoi-su-35s/sukhoi-su-35s-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/sukhoi-su-35s/sukhoi-su-35s-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/sukhoi-su-57/sukhoi-su-57-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/sukhoi-su-57/sukhoi-su-57-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/tupolev-tu-160/tupolev-tu-160-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/tupolev-tu-160/tupolev-tu-160-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/tupolev-tu-22m3/tupolev-tu-22m3-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/tupolev-tu-22m3/tupolev-tu-22m3-02.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/tupolev-tu-95ms/tupolev-tu-95ms-01.png",
  "/assets/suorituskyvyt/03-ilma-avaruusvoimat/tupolev-tu-95ms/tupolev-tu-95ms-02.png"
]
