/**
 * Airborne Forces image paths under public/assets/vehicles/russia/airborne_forces.
 * Generated by: node scripts/list-airborne-forces-images.cjs
 * Do not edit by hand; re-run the script after adding or renaming images.
 */
export const AIRBORNE_FORCES_IMAGE_PATHS: string[] = [
  "/assets/vehicles/russia/airborne_forces/2S25 Sprut-SD/2S25 Sprut-SD_01.png",
  "/assets/vehicles/russia/airborne_forces/2S25 Sprut-SD/2S25 Sprut-SD_02.png",
  "/assets/vehicles/russia/airborne_forces/2S9 Nona-S/2S9 Nona-S_01.png",
  "/assets/vehicles/russia/airborne_forces/2S9 Nona-S/2S9 Nona-S_02.png",
  "/assets/vehicles/russia/airborne_forces/BMD-2/BMD-2_01.png",
  "/assets/vehicles/russia/airborne_forces/BMD-2/BMD-2_02.png",
  "/assets/vehicles/russia/airborne_forces/BMD-4M/BMD-4M_01.png",
  "/assets/vehicles/russia/airborne_forces/BMD-4M/BMD-4M_02.png",
  "/assets/vehicles/russia/airborne_forces/BTR-D/BTR-D_01.png",
  "/assets/vehicles/russia/airborne_forces/BTR-D/BTR-D_02.png",
  "/assets/vehicles/russia/airborne_forces/BTR-MDM Rakushka/BTR-MDM Rakushka_01.png",
  "/assets/vehicles/russia/airborne_forces/BTR-MDM Rakushka/BTR-MDM Rakushka_02.png"
]
