/**
 * Ground Forces image paths under public/assets/vehicles/russia/ground_forces.
 * Generated by: node scripts/list-ground-forces-images.cjs
 * Do not edit by hand; re-run the script after adding or renaming images.
 */
export const GROUND_FORCES_IMAGE_PATHS: string[] = [
  "/assets/vehicles/russia/ground_forces/2s19_msta_s/2s19_msta_s_01.png",
  "/assets/vehicles/russia/ground_forces/2s19_msta_s/2s19_msta_s_02.png",
  "/assets/vehicles/russia/ground_forces/9k720_iskander/9k720_iskander_01.png",
  "/assets/vehicles/russia/ground_forces/9k720_iskander/9k720_iskander_02.png",
  "/assets/vehicles/russia/ground_forces/bm_21_grad/bm_21_grad_01.png",
  "/assets/vehicles/russia/ground_forces/bm_21_grad/bm_21_grad_02.png",
  "/assets/vehicles/russia/ground_forces/bm_30_smerch/bm_30_smerch_01.png",
  "/assets/vehicles/russia/ground_forces/bm_30_smerch/bm_30_smerch_02.png",
  "/assets/vehicles/russia/ground_forces/bmp_2/bmp_2_01.png",
  "/assets/vehicles/russia/ground_forces/bmp_2/bmp_2_02.png",
  "/assets/vehicles/russia/ground_forces/bmp_3/bmp_3_01.png",
  "/assets/vehicles/russia/ground_forces/bmp_3/bmp_3_02.png",
  "/assets/vehicles/russia/ground_forces/btr_82a/btr_82a_01.png",
  "/assets/vehicles/russia/ground_forces/btr_82a/btr_82a_02.png",
  "/assets/vehicles/russia/ground_forces/mt_lb/mt_lb_01.png",
  "/assets/vehicles/russia/ground_forces/mt_lb/mt_lb_02.png",
  "/assets/vehicles/russia/ground_forces/t_72b3/t_72b3_01.png",
  "/assets/vehicles/russia/ground_forces/t_72b3/t_72b3_02.png",
  "/assets/vehicles/russia/ground_forces/t_80bvm/t_80bvm_01.png",
  "/assets/vehicles/russia/ground_forces/t_80bvm/t_80bvm_02.png",
  "/assets/vehicles/russia/ground_forces/t_90m/t_90m_01.png",
  "/assets/vehicles/russia/ground_forces/t_90m/t_90m_02.png"
]
