/**
 * Military district insignia image paths under public/assets/garrisons/military-district-insignia.
 * Generated by: node scripts/list-military-district-insignia-images.cjs
 * Do not edit by hand; re-run the script after adding or renaming images.
 */
export const MILITARY_DISTRICT_INSIGNIA_IMAGE_PATHS: string[] = [
  "/assets/garrisons/military-district-insignia/central_military_district/Central Military District_01.png",
  "/assets/garrisons/military-district-insignia/central_military_district/Central Military District_02.png",
  "/assets/garrisons/military-district-insignia/eastern_military_district/Eastern Military District_01.png",
  "/assets/garrisons/military-district-insignia/eastern_military_district/Eastern Military District_02.png",
  "/assets/garrisons/military-district-insignia/leningrad_military_district/Leningrad Military District_01.png",
  "/assets/garrisons/military-district-insignia/leningrad_military_district/Leningrad Military District_02.png",
  "/assets/garrisons/military-district-insignia/moscow_military_district/Moscow Military District_01.png",
  "/assets/garrisons/military-district-insignia/moscow_military_district/Moscow Military District_02.png",
  "/assets/garrisons/military-district-insignia/northern_fleet_joint_strategic_command/Northern Fleet Joint Strategic Command_01.png",
  "/assets/garrisons/military-district-insignia/northern_fleet_joint_strategic_command/Northern Fleet Joint Strategic Command_02.png",
  "/assets/garrisons/military-district-insignia/southern_military_district/Southern Military District_01.png",
  "/assets/garrisons/military-district-insignia/southern_military_district/Southern Military District_02.png"
]
