/**
 * Strategic Missile Forces image paths under public/assets/vehicles/russia/strategic_missile_forces.
 * Generated by: node scripts/list-strategic-missile-forces-images.cjs
 * Do not edit by hand; re-run the script after adding or renaming images.
 */
export const STRATEGIC_MISSILE_FORCES_IMAGE_PATHS: string[] = [
  "/assets/vehicles/russia/strategic_missile_forces/avangard/avangard_01.png",
  "/assets/vehicles/russia/strategic_missile_forces/rs_24_yars/rs_24_yars_01.png",
  "/assets/vehicles/russia/strategic_missile_forces/rs_24_yars/rs_24_yars_02.png",
  "/assets/vehicles/russia/strategic_missile_forces/rs_28_sarmat/rs_28_sarmat_01.png",
  "/assets/vehicles/russia/strategic_missile_forces/rs_28_sarmat/rs_28_sarmat_02.png",
  "/assets/vehicles/russia/strategic_missile_forces/rt_2pm2_topol_m/rt_2pm2_topol_m_01.png",
  "/assets/vehicles/russia/strategic_missile_forces/rt_2pm2_topol_m/rt_2pm2_topol_m_02.png",
  "/assets/vehicles/russia/strategic_missile_forces/rt_2pm_topol/rt_2pm_topol_01.png",
  "/assets/vehicles/russia/strategic_missile_forces/rt_2pm_topol/rt_2pm_topol_02.png",
  "/assets/vehicles/russia/strategic_missile_forces/ss-18_r_36m2_voyevoda/SS-18_R_36M2_Voyevoda_01.png",
  "/assets/vehicles/russia/strategic_missile_forces/ur_100nuttkh/ur_100nuttkh_01.png",
  "/assets/vehicles/russia/strategic_missile_forces/ur_100nuttkh/ur_100nuttkh_02.png"
]
