/**
 * Taktiset merkit image paths by folder.
 * Generated by: node scripts/list-tactical-signs.cjs (run from project root)
 * Folders: public/assets/tactical-signs/Sotilasmerkistö/ and .../Joukkojen koko/
 * Filename (without extension) = correct answer. Re-run after adding/renaming images.
 */
export const TACTICAL_SIGNS_SOTILASMERKISTO_PATHS: string[] = [
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen CBRN-suojelujaos.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen armeijakunta.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen huoltojoukkue.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen huoltopataljoona.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen ilmatorjuntajoukkue.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen ilmatorjuntakomppania.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen jalkaväkidivisioona.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen jalkaväkipataljoona.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen jalkaväkiprikaati.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen jalkaväkirykmentti.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen kranaatinheitinjoukkue.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen kranaatinheitinpatteristo.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen maahanlaskukomppania.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen maahanlaskupataljoona.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen maihinnousukomppania.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen maihinnousupataljoona.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen mekanisoitu jalkaväkijoukkue.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen mekanisoitu jalkaväkikomppania.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen mekanisoitu jalkaväkipataljoona.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen mekanisoitu tiedustelujoukkue.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen moottoroitu jalkaväkikomppania.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen moottoroitu jalkaväkipataljoona.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen panssarijoukkue.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen panssarintorjuntajoukkue.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen panssarintorjuntapartio.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen panssaripataljoona.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen pioneerijoukkue.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen pioneerikomppania.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen sotilaspoliisipataljoona.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen tiedustelujoukkue.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen tykistöpatteri.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen tykistöpatteristo.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen viestijoukkue.jpg",
  "/assets/tactical-signs/Sotilasmerkistö/Vihollisen viestikomppania.jpg"
]

export const TACTICAL_SIGNS_JOUKKOJEN_KOKO_PATHS: string[] = [
  "/assets/tactical-signs/Joukkojen koko/Armeijakunta - Operatiivinen johtoporras.jpg",
  "/assets/tactical-signs/Joukkojen koko/Divisioona.jpg",
  "/assets/tactical-signs/Joukkojen koko/Joukkue - Jaos - Ruotu - Parvi.jpg",
  "/assets/tactical-signs/Joukkojen koko/Komppania - Patteri - Perustamiskeskus - Viirikö - Lentue.jpg",
  "/assets/tactical-signs/Joukkojen koko/Maavoimat - Rajavartiolaitos - Armeija - Merivoimat - Ilmavoimat.jpg",
  "/assets/tactical-signs/Joukkojen koko/Partio.jpg",
  "/assets/tactical-signs/Joukkojen koko/Pataljoona - Patteristo - Laivue - Linnake.jpg",
  "/assets/tactical-signs/Joukkojen koko/Prikaati - Rajavartiosto - Lippue - Rannikko-alue - Merivartiosto - Lentopiiri.jpg",
  "/assets/tactical-signs/Joukkojen koko/Pääesikunta - Armeijaryhmä - Rintama.jpg.png",
  "/assets/tactical-signs/Joukkojen koko/Ryhmä.jpg",
  "/assets/tactical-signs/Joukkojen koko/Rykmentti - Tykistöryhmä.jpg"
]
