/**
 * Unmanned Systems Forces image paths under public/assets/vehicles/russia/unmanned_system_forces.
 * Generated by: node scripts/list-unmanned-systems-images.cjs
 * Do not edit by hand; re-run the script after adding or renaming images.
 */
export const UNMANNED_SYSTEMS_IMAGE_PATHS: string[] = [
  "/assets/vehicles/russia/unmanned_system_forces/altius/altius_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/eleron/eleron_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/forpost/forpost_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/geran_2/geran_2_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/geran_2/geran_2_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/granat-1/granat_1_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/granat-2/granat_2_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/granat-4/granat_4_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/kub-e/kub_e_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/lancet/lancet_1_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/lancet/lancet_1_012.png",
  "/assets/vehicles/russia/unmanned_system_forces/leer_3/leer_3_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/marker/marker_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/marker/marker_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/nerekhta/nerekhta_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/okhotnik_s_70/okhotnik_s_70_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/okhotnik_s_70/okhotnik_s_70_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/orion_e_inokhodets/orion_e_inokhodets_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/orion_e_inokhodets/orion_e_inokhodets_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/orlan_10/orlan_10_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/orlan_10/orlan_10_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/orlan_30/orlan_30_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/orlan_30/orlan_30_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/supercam_s150/supercam_s150_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/supercam_s150/supercam_s150_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/supercam_s350/supercam_s350_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/supercam_s350/supercam_s350_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/takhion/takhion_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/takhion/takhion_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/uran_9/uran_9_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/uran_9/uran_9_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/zala_421_08/zala_421_08_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/zala_421_08/zala_421_08_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/zala_421_16/zala_421_16e_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/zala_421_16/zala_421_16e_02.png",
  "/assets/vehicles/russia/unmanned_system_forces/zala_421_22/zala_421_22_01.png",
  "/assets/vehicles/russia/unmanned_system_forces/zala_421_22/zala_421_22_02.png"
]
